FROM shimforge-test:local

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc-aarch64-linux-gnu qemu-user \
    && rustup target add aarch64-unknown-linux-gnu \
    && rustup target add --toolchain 1.85.0 aarch64-unknown-linux-gnu

ENV CARGO_BUILD_TARGET=aarch64-unknown-linux-gnu
ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUNNER="qemu-aarch64 -L /usr/aarch64-linux-gnu"
